// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fpt_backend.Data;

#nullable disable

namespace fpt_backend.Migrations
{
    [DbContext(typeof(FptDbContext))]
    [Migration("20251106203341_Added more models")]
    partial class Addedmoremodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipmentExercise", b =>
                {
                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("ExercisesExerciseId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId", "ExercisesExerciseId");

                    b.HasIndex("ExercisesExerciseId");

                    b.ToTable("EquipmentExercise");
                });

            modelBuilder.Entity("ExerciseMuscle", b =>
                {
                    b.Property<int>("ExercisesExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("MusclesMuscleId")
                        .HasColumnType("int");

                    b.HasKey("ExercisesExerciseId", "MusclesMuscleId");

                    b.HasIndex("MusclesMuscleId");

                    b.ToTable("ExerciseMuscle");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GloballyVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.ExerciseSession", b =>
                {
                    b.Property<int>("ExerciseSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseSessionId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkoutProgramId")
                        .HasColumnType("int");

                    b.HasKey("ExerciseSessionId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("ExerciseSessions");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.ExerciseSessionRecord", b =>
                {
                    b.Property<int>("ExerciseSessionRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseSessionRecordId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseSetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.HasKey("ExerciseSessionRecordId");

                    b.ToTable("ExerciseSessionRecords");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.ExerciseSet", b =>
                {
                    b.Property<int>("ExerciseSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseSetId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RepCeiling")
                        .HasColumnType("int");

                    b.Property<int>("RepFloor")
                        .HasColumnType("int");

                    b.HasKey("ExerciseSetId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("ExerciseSessionId");

                    b.ToTable("ExerciseSets");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.ExerciseSetRecord", b =>
                {
                    b.Property<int>("ExerciseSetRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseSetRecordId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExerciseSessionId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseSessionRecordId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseSetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("ExerciseSetRecordId");

                    b.HasIndex("ExerciseSessionId");

                    b.HasIndex("ExerciseSessionRecordId");

                    b.HasIndex("ExerciseSetId");

                    b.ToTable("ExerciseSetRecords");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Muscle", b =>
                {
                    b.Property<int>("MuscleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuscleId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("MuscleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MuscleId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("Muscles");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.MuscleGroup", b =>
                {
                    b.Property<int>("MuscleGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuscleGroupId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("MuscleGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MuscleGroupId");

                    b.ToTable("MuscleGroups");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.WorkoutProgram", b =>
                {
                    b.Property<int>("WorkoutProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkoutProgramId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("HasAccessToProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkoutProgramDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkoutProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkoutProgramId");

                    b.ToTable("WorkoutPrograms");
                });

            modelBuilder.Entity("EquipmentExercise", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fpt_backend.Data.Models.GymModels.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExerciseMuscle", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fpt_backend.Data.Models.GymModels.Muscle", null)
                        .WithMany()
                        .HasForeignKey("MusclesMuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.ExerciseSession", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.Exercise", null)
                        .WithMany("ExerciseSessions")
                        .HasForeignKey("ExerciseId");

                    b.HasOne("fpt_backend.Data.Models.GymModels.WorkoutProgram", null)
                        .WithMany("ExerciseSessions")
                        .HasForeignKey("WorkoutProgramId");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.ExerciseSet", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fpt_backend.Data.Models.GymModels.ExerciseSession", "ExerciseSession")
                        .WithMany("ExerciseSets")
                        .HasForeignKey("ExerciseSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("ExerciseSession");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.ExerciseSetRecord", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.ExerciseSession", null)
                        .WithMany("ExerciseSetRecords")
                        .HasForeignKey("ExerciseSessionId");

                    b.HasOne("fpt_backend.Data.Models.GymModels.ExerciseSessionRecord", "ExerciseSessionRecord")
                        .WithMany("ExerciseSetRecords")
                        .HasForeignKey("ExerciseSessionRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fpt_backend.Data.Models.GymModels.ExerciseSet", "ExerciseSet")
                        .WithMany("ExerciseSetRecords")
                        .HasForeignKey("ExerciseSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseSessionRecord");

                    b.Navigation("ExerciseSet");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Muscle", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.MuscleGroup", "MuscleGroup")
                        .WithMany("Muscles")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Exercise", b =>
                {
                    b.Navigation("ExerciseSessions");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.ExerciseSession", b =>
                {
                    b.Navigation("ExerciseSetRecords");

                    b.Navigation("ExerciseSets");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.ExerciseSessionRecord", b =>
                {
                    b.Navigation("ExerciseSetRecords");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.ExerciseSet", b =>
                {
                    b.Navigation("ExerciseSetRecords");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.MuscleGroup", b =>
                {
                    b.Navigation("Muscles");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.WorkoutProgram", b =>
                {
                    b.Navigation("ExerciseSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
