// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fpt_backend.Data;

#nullable disable

namespace fpt_backend.Migrations
{
    [DbContext(typeof(FptDbContext))]
    [Migration("20260206212039_Description set to nullable")]
    partial class Descriptionsettonullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipmentExercise", b =>
                {
                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("ExercisesId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId", "ExercisesId");

                    b.HasIndex("ExercisesId");

                    b.ToTable("EquipmentExercise");
                });

            modelBuilder.Entity("ExerciseMuscle", b =>
                {
                    b.Property<int>("ExercisesId")
                        .HasColumnType("int");

                    b.Property<int>("MusclesId")
                        .HasColumnType("int");

                    b.HasKey("ExercisesId", "MusclesId");

                    b.HasIndex("MusclesId");

                    b.ToTable("ExerciseMuscle");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GloballyVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.ExerciseSetRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RepsCompleted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SetId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("ExerciseSetRecord");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Instances.ExerciseSetBlocTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseSetBlocTemplate");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Instances.ExerciseSetTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExerciseSetBlocTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseSetBlocTemplateId");

                    b.ToTable("ExerciseSetTemplate");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Instances.SessionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SessionTemplate");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Instances.SetTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("RepCeiling")
                        .HasColumnType("int");

                    b.Property<int>("RepFloor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SetTemplate");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Instances.WorkoutProgrammeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutProgrammeTemplate");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.JoiningModels.SessionTemplateSetBlocTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("SetBlocTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionTemplateId");

                    b.HasIndex("SetBlocTemplateId");

                    b.ToTable("SessionTemplateSetBlocTemplate");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.JoiningModels.WorkoutProgrammeTemplateSessionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SessionTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutProgrammeTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionTemplateId");

                    b.HasIndex("WorkoutProgrammeTemplateId");

                    b.ToTable("WorkoutProgrammeTemplateSessionTemplate");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("MuscleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("Muscles");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("MuscleGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SessionTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutProgrammeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("SessionTemplateId");

                    b.HasIndex("WorkoutProgrammeId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("RepCeiling")
                        .HasColumnType("int");

                    b.Property<int>("RepFloor")
                        .HasColumnType("int");

                    b.Property<int>("SetBlocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetBlocId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.SetBloc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int?>("SetBlocTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SetBlocTemplateId");

                    b.ToTable("SetBlocs");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.WorkoutProgramme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkoutProgrammeTemplateID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutProgrammeTemplateID");

                    b.ToTable("WorkoutProgrammes");
                });

            modelBuilder.Entity("EquipmentExercise", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fpt_backend.Data.Models.GymModels.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExerciseMuscle", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fpt_backend.Data.Models.GymModels.Muscle", null)
                        .WithMany()
                        .HasForeignKey("MusclesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.ExerciseSetRecord", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.Set", "Set")
                        .WithMany("ExerciseSetRecords")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Instances.ExerciseSetTemplate", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.Instances.ExerciseSetBlocTemplate", null)
                        .WithMany("Sets")
                        .HasForeignKey("ExerciseSetBlocTemplateId");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.JoiningModels.SessionTemplateSetBlocTemplate", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.Instances.SessionTemplate", "SessionTemplate")
                        .WithMany("SetBlocs")
                        .HasForeignKey("SessionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fpt_backend.Data.Models.GymModels.Instances.ExerciseSetBlocTemplate", "SetBlocTemplate")
                        .WithMany("SessionTemplates")
                        .HasForeignKey("SetBlocTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionTemplate");

                    b.Navigation("SetBlocTemplate");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.JoiningModels.WorkoutProgrammeTemplateSessionTemplate", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.Instances.SessionTemplate", "SessionTemplate")
                        .WithMany("WorkoutProgrammeTemplates")
                        .HasForeignKey("SessionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fpt_backend.Data.Models.GymModels.Instances.WorkoutProgrammeTemplate", "WorkoutProgrammeTemplate")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkoutProgrammeTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionTemplate");

                    b.Navigation("WorkoutProgrammeTemplate");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Muscle", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.MuscleGroup", "MuscleGroup")
                        .WithMany("Muscles")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Session", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.Exercise", null)
                        .WithMany("ExerciseSessions")
                        .HasForeignKey("ExerciseId");

                    b.HasOne("fpt_backend.Data.Models.GymModels.Instances.SessionTemplate", "SessionTemplate")
                        .WithMany()
                        .HasForeignKey("SessionTemplateId");

                    b.HasOne("fpt_backend.Data.Models.GymModels.WorkoutProgramme", "WorkoutProgramme")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkoutProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionTemplate");

                    b.Navigation("WorkoutProgramme");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Set", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.SetBloc", "SetBloc")
                        .WithMany("Sets")
                        .HasForeignKey("SetBlocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SetBloc");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.SetBloc", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.Session", "Session")
                        .WithMany("SetBlocs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fpt_backend.Data.Models.GymModels.Instances.ExerciseSetBlocTemplate", "SetBlocTemplate")
                        .WithMany()
                        .HasForeignKey("SetBlocTemplateId");

                    b.Navigation("Session");

                    b.Navigation("SetBlocTemplate");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.WorkoutProgramme", b =>
                {
                    b.HasOne("fpt_backend.Data.Models.GymModels.Instances.WorkoutProgrammeTemplate", "WorkoutProgrammeTemplate")
                        .WithMany()
                        .HasForeignKey("WorkoutProgrammeTemplateID");

                    b.Navigation("WorkoutProgrammeTemplate");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Exercise", b =>
                {
                    b.Navigation("ExerciseSessions");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Instances.ExerciseSetBlocTemplate", b =>
                {
                    b.Navigation("SessionTemplates");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Instances.SessionTemplate", b =>
                {
                    b.Navigation("SetBlocs");

                    b.Navigation("WorkoutProgrammeTemplates");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Instances.WorkoutProgrammeTemplate", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.MuscleGroup", b =>
                {
                    b.Navigation("Muscles");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Session", b =>
                {
                    b.Navigation("SetBlocs");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.Set", b =>
                {
                    b.Navigation("ExerciseSetRecords");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.SetBloc", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("fpt_backend.Data.Models.GymModels.WorkoutProgramme", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
